# Generated by Django 5.1.2 on 2024-11-03 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('otp', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_verifed', models.BooleanField(default=False)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=250)),
                ('job_description', models.CharField(max_length=5000)),
                ('company_information', models.CharField(max_length=5000)),
                ('qualification', models.CharField(max_length=250)),
                ('responsibilities', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=250)),
                ('selary_packege', models.CharField(max_length=250)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('experience', models.IntegerField()),
                ('company_website', models.CharField(max_length=250)),
                ('company_email', models.EmailField(max_length=250)),
                ('company_contact', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=50)),
                ('ceo', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='app/img/company')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=150)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('h_rate', models.BigIntegerField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('profile', models.ImageField(upload_to='app/img/candidate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master')),
            ],
        ),
    ]
