# Generated by Django 5.1.2 on 2024-11-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_details_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('protfolio', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('minSelary', models.CharField(max_length=200)),
                ('maxSelary', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='app/img/candidate_cv')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_details')),
            ],
        ),
    ]
