# Generated by Django 5.1.2 on 2024-11-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
